version: "3.8"

services:
  frontend:
    build:
      context: ./ProxmoxDashboard
    image: frontend
    restart: unless-stopped
    ports:
      - "8050:80"
    networks:
      - custom-network

  backend:
    build:
      context: ./ProxmoxApi
    image: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - custom-network

networks:
    custom-network:
        driver: bridge
        name: custom-network